name: Check docs build

on:
  pull_request:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install UV
      uses: astral-sh/setup-uv@v5
      with:
        pyproject-file: "pyproject.toml"
        python-version: '3.11'

    - name: Install dependencies with UV
      run: uv sync --all-groups 

    - name: Generate API documentation
      run: uv run sphinx-apidoc -o docs/apidocs helix

    - name: Build HTML documentation
      working-directory: docs
      run: make html
