name: Reusable docs builder workflow

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies with Poetry
      run: |
        poetry install

    - name: Generate API documentation
      run: |
        poetry run sphinx-apidoc -o docs/apidocs biofefi

    - name: Build HTML documentation
      working-directory: docs
      run: make html

    - name: Upload artifacts (optional)
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: docs/_build/html
