name: Run Unit Tests

on:
  - pull_request

jobs:
  run_unit_tests:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
       with:
         submodules: 'recursive'
         ref: ${{ github.ref }}
     - name: Install UV
       uses: astral-sh/setup-uv@v5
       with:
        pyproject-file: "pyproject.toml"
        python-version: '3.11'
     - name: Install dependencies
       run: uv sync --all-groups
     - name: Run pytest
       run: uv run pytest --ignore tests/pages/test_5_Feature_Importance.py